README.md

The artefact is not published to jcenter yet, so the `dl.bintray.com` thing is necessary here.
The 'latest version badge' in the header came from https://bintray.com/palantir/releases/docker-compose-rule/view.

Add gradle bintray dependency example to README

---

src/main/java/com/palantir/docker/compose/connection/Container.java

Previously creating a new HealthCheck was a little frustrating to do via Lambdas because of unnecessary Exception declarations in method headers.

Improve ease of creating new HealthChecks.

---

src/main/java/com/palantir/docker/compose/connection/Container.java
src/main/java/com/palantir/docker/compose/connection/waiting/HealthCheck.java
src/main/java/com/palantir/docker/compose/connection/waiting/HealthChecks.java
src/main/java/com/palantir/docker/compose/connection/waiting/ServiceWait.java
src/main/java/com/palantir/docker/compose/connection/waiting/SuccessOrFailure.java
src/test/java/com/palantir/docker/compose/DockerCompositionTest.java
src/test/java/com/palantir/docker/compose/connection/ContainerTest.java
src/test/java/com/palantir/docker/compose/connection/waiting/HttpHealthCheckShould.java
src/test/java/com/palantir/docker/compose/connection/waiting/PortsHealthCheckShould.java
src/test/java/com/palantir/docker/compose/connection/waiting/SuccessOrFailureMatchers.java
src/test/java/com/palantir/docker/compose/connection/waiting/SuccessOrFailureShould.java

Tired of just seeing `Container 'myContainer' failed to pass startup check` rather than *why* it failed the startup check, I've now made it so that healthchecks return an error as well as if it succeeded or failed.

Healthchecks should give error messages

---

src/main/java/com/palantir/docker/compose/execution/DefaultDockerCompose.java

Currently my build platform gives me the exception message in one block in a nice place. Logging the output separately to exception means I have to hunt it down in the logs. This way the output is included with the exception so you can easily debug.

Put `docker-compose` output directly into exception message

---

src/main/java/com/palantir/docker/compose/configuration/DockerType.java
src/main/java/com/palantir/docker/compose/connection/DockerMachine.java
src/test/java/com/palantir/docker/compose/configuration/DockerTypeTest.java

Fixes #68 by providing ability to set LocalMachine
to be explicitly set to DAEMON regardless of platform.

Allow DockerType to be specified in localMachine

---

src/main/java/com/palantir/docker/compose/connection/DockerPort.java

A service can open a port before it's ready to accept SSL connections.
Not sure how I'd go about testing this one.

Don't assume that an SSL exception when health checking a container means it's up.

---

src/main/java/com/palantir/docker/compose/execution/Command.java
src/test/java/com/palantir/docker/compose/execution/CommandShould.java

I was trying to use docker-compose-rule with [Java Microbenchmarking Harness (JMH)](http://openjdk.java.net/projects/code-tools/jmh/) and found that docker-compose-rule uses non-daemon threads (probably okay) and does not explicitly shutdown these associated pools (probably bad).  I hit this with JMH because JMH forks JVMs and complains when the spawned JVMs do not shutdown normally.  The project (the one using JMH) uses docker-compose-rule in non-test code (probably not how it was originally intended), but everything else worked smoothly minus this particular hiccup.

do not prevent jvm shutdown due to empty thread pools

---

src/main/java/com/palantir/docker/compose/DockerComposeRule.java
src/main/java/com/palantir/docker/compose/DockerComposition.java
src/main/java/com/palantir/docker/compose/execution/DefaultDockerCompose.java
src/main/java/com/palantir/docker/compose/execution/DelegatingDockerCompose.java
src/main/java/com/palantir/docker/compose/execution/DockerCompose.java
src/main/java/com/palantir/docker/compose/execution/DockerComposeExecArgument.java
src/main/java/com/palantir/docker/compose/execution/DockerComposeExecOption.java
src/main/java/com/palantir/docker/compose/execution/DockerComposeRunArgument.java
src/main/java/com/palantir/docker/compose/execution/DockerComposeRunOption.java
src/test/java/com/palantir/docker/compose/DockerCompositionIntegrationTest.java
src/test/java/com/palantir/docker/compose/execution/DockerComposeShould.java
src/test/java/com/palantir/docker/compose/execution/RetryingDockerComposeShould.java

Add support for calling docker-compose run. This feature is needed so we can work around the CircleCI issue of not being able to use ```lxc-attach``` or ```docker exec``` on docker 1.10 and higher.

Add support for calling docker-compose run

---

src/main/java/com/palantir/docker/compose/connection/Container.java
src/main/java/com/palantir/docker/compose/execution/DefaultDockerCompose.java
src/main/java/com/palantir/docker/compose/execution/DelegatingDockerCompose.java
src/main/java/com/palantir/docker/compose/execution/DockerCompose.java
src/test/java/com/palantir/docker/compose/DockerCompositionIntegrationTest.java

Stop(Container) sends a SIGTERM followed by a SIGKILL to a container that allows time for graceful shutdown. We want to kill a node i.e. a container to simulate node dying. 
Your PR should contain a few sentences describing what problem your PR solves.

Add method to kill a container

---

src/main/java/com/palantir/docker/compose/Depluralized.java
src/main/java/com/palantir/docker/compose/DockerComposeRule.java

This PR fixes a compile warning concerning `depluralize()`. It is the same issue that was addressed here: https://github.com/palantir/docker-compose-rule/commit/d929d35e936ae6915a2f3ff8924e87fba9a4d888

Fix depluralize() compile warning

---

README.md
build.gradle
src/main/java/com/palantir/docker/compose/DockerComposeRule.java
src/main/java/com/palantir/docker/compose/logging/LogDirectory.java
src/test/java/com/palantir/docker/compose/logging/LogDirectoryTest.java

I've been using this little utility method to debug some tricky circle CI builds, so thought it's worth contributing back.

New `circleAwareLogDirectory` enables partial log capture on CI

---

src/main/java/com/palantir/docker/compose/logging/LogDirectory.java
src/test/java/com/palantir/docker/compose/logging/LogDirectoryTest.java

This solves the case when multiple classes have the same name, or the rule is part of a superclass

Add string version of circleAwareLogDirectory.

---

src/main/java/com/palantir/docker/compose/CustomImmutablesStyle.java
src/main/java/com/palantir/docker/compose/DockerComposeRule.java
src/test/java/com/palantir/docker/compose/DockerComposeRuleShould.java

This removes a few generated methods too, e.g, you can no longer initialise a builder `from` an existing instance.
fixes #118

Switch to immutables strict builder

---

src/main/java/com/palantir/docker/compose/execution/DockerComposeExecOption.java
src/test/java/com/palantir/docker/compose/execution/DockerComposeExecOptionShould.java

Fixed up checkstyle problems from #114.
> Non-breaking change to fix an overloading bug.
> 
> Fixes #113.
> 
> 34d64fe made the protected instance method options() public, which
> makes it clash with the public static method options(String...) in the
> frequent case you don't want to pass any options.
> 
> This PR adds a noOptions() method which avoids this kind of bad
> behaviour.
> 
> I did this because everything else would break at least one person. More
> generally, it's probably advisable to try to name static methods
> differently to instance methods, or you open yourself up to these
> overloading based bugs.

Add a noOptions method to DockerComposeExecOption

---

LICENSE

The brackets are in the section on re-applying the license, so it is correct to have them.

Revert incorrect change to LICENSE

---

src/main/java/com/palantir/docker/compose/connection/DockerMachine.java
src/test/java/com/palantir/docker/compose/connection/LocalBuilderShould.java

The docker reserved variables (DOCKER_TLS_VERIFY, DOCKER_HOST,
DOCKER_CERT_PATH) are still not allowed in additionalEnvironment.
But the user can now override their own environment variables
programatically. (See AtlasDB PR 1237).
Fixes #131.

LocalBuilder: Allow additionalEnvironment to override systemEnvironment

---

docker-compose-rule-core/src/main/java/com/palantir/docker/compose/connection/Container.java
docker-compose-rule-core/src/main/java/com/palantir/docker/compose/connection/DockerPort.java
docker-compose-rule-core/src/main/java/com/palantir/docker/compose/connection/waiting/HealthChecks.java
docker-compose-rule-core/src/test/java/com/palantir/docker/compose/configuration/MockDockerEnvironment.java

By default "waiting for cluster to be healthy" will assume that a 404 response is OK. 
In some cases this can be tricky (e.g. waiting for larger-than-usual web applications to deploy before starting the actual test).
Add a new method that will also check for status 200.

Optionally don't accept status code 404 as "healthy"

---

docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/DockerComposeExecutable.java
docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/DockerForMacHostsIssue.java

As per [docker issue #3419](https://github.com/docker/compose/issues/3419#issuecomment-221793401), Docker for Mac uses "localunixsocket" instead of "localhost" to resolve sockets, which causes an order of magnitude slowdown (85s vs 5s for LoggingIntegrationTests on my laptop) unless it is explicitly redirected to 127.0.0.1 in /etc/hosts. Check for this condition, and issue a clear warning once per test run.

Warn if Docker for Mac is likely to be slow

---

docker-compose-rule-core/src/main/java/com/palantir/docker/compose/configuration/ShutdownStrategy.java
docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/KillDownShutdownStrategy.java
docker-compose-rule-core/src/test/java/com/palantir/docker/compose/execution/KillDownShutdownStrategyShould.java
docker-compose-rule-junit4/src/main/java/com/palantir/docker/compose/DockerComposeRule.java
docker-compose-rule-junit4/src/test/resources/docker-compose.yaml

Most Docker containers ignore the SIGTERM they are sent by 'docker-compose down', resulting in a pointless 10 second delay per test. The 'aggressive' shutdown strategies are unnecessarily complex, however, as we can simply issue a 'docker-compose kill' first, and rely on 'docker-compose down' to clean up gracefully. There is also no need to issue a 'docker-compose rm' as we already pass '--volumes' to 'down'. This new KillDownShutdownStrategy should be safe for us to default users to.

Speed up test teardown

---

docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/Docker.java

Using version 0.31.0 and the latest stable docker release (version 1.13.1) on Windows, both of the tests in ContainerIntegrationTests fail with the following error:
```
com.palantir.docker.compose.execution.DockerExecutionException: 'docker inspect --format={{if not .State.Running}}DOWN{{else if .State.Paused}}PAUSED{{else if index .State "Health"}}{{if eq .State.Health.Status "healthy"}}HEALTHY{{else}}UNHEALTHY{{end}}{{else}}HEALTHY{{end}} 0f0d3e40ef642d0b1201f23e50994d531c33e44fd7f05104dd111d98bdf0dd57' returned exit code 64
The output was:
Template parsing error: template: :1: function "Health" not defined
```
This is down to the way the double-quotes need to be escaped in windows, which is to use the back-tick. My commit performs this escaping when running on Windows.

Fix docker health check to work on Windows.

---

docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/DefaultDockerCompose.java
docker-compose-rule-core/src/test/java/com/palantir/docker/compose/execution/DockerComposeShould.java

Calls to docker-compose exec in Windows need the -T option (to disable
pseudo-tty allocation, which doesn't work in Windows without something
like winpty).
This commit adds the -T option to all calls to docker-compose exec.
Is there any reason not to disable pseudo-tty allocation? If so I could only add "-T" if on Windows.

Fix call to docker-compose exec in integration test.

---

docker-compose-rule-core/src/main/java/com/palantir/docker/compose/connection/ContainerNames.java
docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/DefaultDockerCompose.java
docker-compose-rule-core/src/test/java/com/palantir/docker/compose/connection/ContainerNameShould.java

This fixes most integration tests on Windows (still a few more to go though!)

Fix regex for splitting on newline characters to work on Windows too.

---

docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/Retryer.java

**Reasoning**
Was pretty tricky to work out exactly what was going on from DockerComposeRule logs from CircleCI as things got mushed together with DockerCompose error output.
**Changes**
- Ensure newline is printed between docker output and Retrying log mess…ages.
- Add log line when all retries are exhausted.
Also wondering whether you want to add tests for log messages?

Slightly improved logging for Retryer.

---

docker-compose-rule-junit4/src/test/java/com/palantir/docker/compose/HostNetworkedPortsIntegrationTest.java

This commit uses JUnit's assumptions to ignore the
HostNetworkedPortsIntegrationTest on any OS but linux.
Ports exposed on the "host" network are accessible on linux because the host
is running on localhost. On Windows and Mac, the host is instead running on a
linux VM and the ports are not accessible.

Ignore test that fails on Windows/Mac by design.

---

docker-compose-rule-core/src/test/java/com/palantir/docker/compose/connection/ContainerIntegrationTests.java

This prevents the test from intermittently failing when the health status took
longer than 1s to be updated.

Increase timeout in ContainerIntegrationTests from 1s to 10s.

---

docker-compose-rule-junit4/src/test/java/com/palantir/docker/compose/RemoveConflictingContainersIntegrationTest.java

This makes sure the containers created in
`RemoveConflictingContainersIntegrationTest` are deleted after each method.
The containers left over by this test can then make the test fail when it gets run again (since the test uses `removeConflictingContainersOnStartup(false)`). After this commit, doing a full build results in no containers being left over.

Delete containers left over from an integration test.

---

docker-compose-rule-core/src/main/java/com/palantir/docker/compose/connection/Container.java
docker-compose-rule-junit4/src/test/java/com/palantir/docker/compose/HostNetworkedPortsIntegrationTest.java

We recently had a mysterious failure that was hard to debug because we had two containers binding to the same port.

Better error message on container failing to listen to a port

---

docker-compose-rule-core/src/main/java/com/palantir/docker/compose/connection/Container.java
docker-compose-rule-core/src/test/java/com/palantir/docker/compose/configuration/MockDockerEnvironment.java
docker-compose-rule-core/src/test/java/com/palantir/docker/compose/connection/ContainerShould.java

Port mappings can be different after restarting a docker container, i.e. when it's services uses ports in the ephemeral range. This means that the mapping needs to be re-evaluated upon (re)start of the container.

Fixed issue with memoized ports upon (re)start of docker container

---

docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/AggressiveShutdownStrategy.java
docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/AggressiveShutdownWithNetworkCleanupStrategy.java
docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/Docker.java
docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/GracefulShutdownStrategy.java
docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/KillDownShutdownStrategy.java
docker-compose-rule-core/src/test/java/com/palantir/docker/compose/execution/DockerShould.java
docker-compose-rule-core/src/test/java/com/palantir/docker/compose/execution/GracefulShutdownStrategyShould.java
docker-compose-rule-core/src/test/java/com/palantir/docker/compose/execution/KillDownShutdownStrategyShould.java

This is a harmless operation, [only removing networks not in use](https://docs.docker.com/engine/reference/commandline/network_prune/#extended-description)
_"Remove all unused networks. Unused networks are those which are not referenced by any containers."_
There is also however an argument for doing a [system prune](https://docs.docker.com/engine/reference/commandline/system_prune). What are your thoughts @iamdanfox ?
On one hand this will require re-downloading of images **every single time** but on the other it's a good way of guaranteeing a truly stateless setup? :)

Added network pruning to all shutdown strategies 

---

changelog/@unreleased/pr-299.v2.yml
docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/DefaultDockerCompose.java
docker-compose-rule-core/src/main/java/com/palantir/docker/compose/logging/FileLogCollector.java
docker-compose-rule-core/src/test/java/com/palantir/docker/compose/logging/FileLogCollectorShould.java

#293 broke log collection because the we time out the log collection after 50ms. This made sense when we were streaming logs but not after we changed the behavior to collect at the end.
We now give the logs process 1 minute to collect logs before timing out.

Increase timeout and simplify log collection

---

docker-compose-rule-junit4/build.gradle
docker-compose-rule-junit4/src/integrationTest/java/com/palantir/docker/compose/HostNetworkedPortsIntegrationTest.java

Integration tests are not running as part of the build - they got disabled somehow, maybe in the recent circle 2/circle-templates upgrade
Integration tests are running once again.

Re-enable integration tests on master

---

changelog/@unreleased/pr-301.v2.yml
docker-compose-rule-core/src/main/java/com/palantir/docker/compose/CustomImmutablesStyle.java
docker-compose-rule-junit4/src/main/java/com/palantir/docker/compose/DockerComposeRule.java
docker-compose-rule-junit4/src/test/java/com/palantir/docker/compose/DockerComposeRuleShould.java

`DockerComposeRule.builder()` returns a final `ImmutableDockerComposeRule` rather than a `DockerComposeRule`. This prevents us from transparently wrapping `DockerComposeRule` internally to record metrics from it.
==COMMIT_MSG==
`overshadowImplementation` is enabled for all docker-compose-rule builders. Any uses of `ImmutableDockerComposeRule` as returned from `DockerComposeRule.builder()` will now no longer compile. To fix, please use `DockerComposeRule` instead of `ImmutableDockerComposeRule`.
==COMMIT_MSG==
Some peoples (<5 projects) code will break: https://github.com/search?q=ImmutableDockerComposeRule&type=Code. No instances of this happening internally in non-archived projects.

[break] Turn on overshadowImplementation for builders

---

docker-compose-rule-core/src/integrationTest/java/com/palantir/docker/compose/AggressiveShutdownWithNetworkCleanupStrategyIntegrationTest.java

The master branch is failing since https://circleci.com/workflow-run/5e458cfe-cb9d-4c55-8fb4-71e6e4685930 with the test `AggressiveShutdownWithNetworkCleanupStrategyIntegrationTest.clean_up_created_networks_when_shutting_down` being broken. Verified that a previous green build is now red, so this must be a circleci change.
The test is ignored to get master green again.

Fix master branch

---

changelog/@unreleased/pr-322.v2.yml
docker-compose-rule-core/src/main/java/com/palantir/docker/compose/reporting/GitUtils.java
docker-compose-rule-core/src/main/java/com/palantir/docker/compose/reporting/ReportCompiler.java
docker-compose-rule-core/src/test/java/com/palantir/docker/compose/reporting/GitUtilsTest.java
docker-compose-rule-events-api/src/main/conjure/report-api.yml
versions.lock
versions.props

Reports do not have the path of the git repo being used included in it, so we cannot tell which repo people are using DCR on.
==COMMIT_MSG==
Stats reporting will now send the path of the origin git url.
==COMMIT_MSG==
Accidentally scoop up a sensitive token or similar that's in the remote url. There is a test for the format we use for this internally. Also people have to opt-in to this codepath by creating a `.docker-compose-rule.yml` file anyway, so we won't impact real OSS users.

Add origin git remote url path to reports

---

docker-compose-junit-jupiter/src/main/java/com/palantir/docker/compose/DockerComposeExtension.java
docker-compose-rule-core/src/main/java/com/palantir/docker/compose/DockerComposeManager.java
docker-compose-rule-junit4/src/main/java/com/palantir/docker/compose/DockerComposeRule.java

Lots of duplication of logic in various builders
By inverting how BuilderExtensions work we can have the individual builders inherit the common behaviour

Remove duplication by inverting BuilderExtensions control

---

README.md
docker-compose-junit-jupiter/src/integrationTest/java/com/palantir/docker/compose/DockerComposeExtensionIntegrationTest.java
docker-compose-junit-jupiter/src/main/java/com/palantir/docker/compose/DockerComposeExtension.java

DockerComposeExtension would try and spinup/tear down containers around every single @Test method.  This is actually a very uncommon use-case internally (like 4 usages or @Rule compared to >700 of @ClassRule).
==COMMIT_MSG==
DockerComposeExtension implements BeforeAllCallback, to ensure containers are started up once at the beginning of the test class
==COMMIT_MSG==
annoyingly the JUnit5 APIs don't give us flexibility to support both choices, so we're stuck with picking one for now

junit5 DockerComposeExtension should be a @ClassRule equivalent (also docs)

---

changelog/@unreleased/pr-425.v2.yml
docker-compose-rule-core/src/main/java/com/palantir/docker/compose/connection/Container.java
docker-compose-rule-core/src/test/java/com/palantir/docker/compose/connection/ContainerShould.java

When `Container#port` throws an IllegalArgumentException, the message contains the lambda that gets the port mappings as opposed to the mappings themselves. For example (scroll right):
```
java.lang.IllegalArgumentException: No internal port '8107' for container '<redacted>': com.palantir.docker.compose.connection.Container$$Lambda$139/0x000000080026e040@5e9b4687
at com.palantir.docker.compose.connection.Container.lambda$port$4(Container.java:91)
at java.base/java.util.Optional.orElseThrow(Optional.java:408)
at com.palantir.docker.compose.connection.Container.port(Container.java:91)
...
```
==COMMIT_MSG==
Include port mappings in exception thrown when failing to resolve a port.
==COMMIT_MSG==

Actually print port mappings

---

changelog/@unreleased/pr-424.v2.yml
docker-compose-rule-core/src/main/java/com/palantir/docker/compose/connection/DockerMachine.java

Newer versions of docker-compose (at least 1.25.0-rc4) adjust the output based on the number of columns available in the terminal. This interferes with parsing of the output and can cause errors like "No internal port X for container Y" when the port does exist.  This is because of a parse failure while parsing the output of `docker-compose ps`.
==COMMIT_MSG==
Set the `COLUMNS` environment variable to an artificially large value for the `docker-compose` process.  This works around newer versions of docker-compose (at least 1.25.0-rc4+) which adjust their output based on the width of the terminal.
==COMMIT_MSG==

Fix parsing of docker-compose output.

---

changelog/@unreleased/pr-495.v2.yml
docker-compose-rule-core/src/main/java/com/palantir/docker/compose/configuration/ProjectName.java
docker-compose-rule-core/src/test/java/com/palantir/docker/compose/configuration/ProjectNameShould.java

If not set, the `ProjectName` uses `ProjectName#random` to set the docker-compose project name.
In some cases, you want to omit the project name entirely, which makes docker-compose use the name of its current directory as the project name ([reference](https://docs.docker.com/compose/reference/overview/#use--p-to-specify-a-project-name)).
Allow omitting the project name by using `ProjectName#omit`:
```java
DockerComposeExtension.Builder builder = DockerComposeExtension.builder()
.file("../docker-compose.yml")
.projectName(ProjectName.omit())
.build();
```
In this case docker-compose will be run without the `--project-name` option. 
==COMMIT_MSG==
Add option to omit the project name
==COMMIT_MSG==

Add option to omit the project name

---

changelog/@unreleased/pr-695.v2.yml
docker-compose-rule-core/src/main/java/com/palantir/docker/compose/connection/Ports.java
docker-compose-rule-core/src/test/java/com/palantir/docker/compose/connection/PortsShould.java

Port ranges from docker ps output weren't mapped
==COMMIT_MSG==
Map port range mappings from docker ps output
==COMMIT_MSG==
Fixes https://github.com/palantir/docker-compose-rule/issues/689

match port range output from docker ps

---

changelog/@unreleased/pr-729.v2.yml
docker-compose-rule-core/src/integrationTest/java/com/palantir/docker/compose/RemoveConflictingContainersIntegrationTest.java
docker-compose-rule-core/src/main/java/com/palantir/docker/compose/DockerComposeManager.java

==COMMIT_MSG==
Enable docker-compose v2 by default, since it's present in internal and external circle
==COMMIT_MSG==

Use docker compose v2 by default

---

changelog/@unreleased/pr-732.v2.yml
docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/ConflictingContainerRemovingDockerCompose.java
docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/DockerExecutionException.java

If docker-compose up fails due to container name conflicts, that information is hidden in debug logs, which are rarely turned on by default.
==COMMIT_MSG==
Include lastException as cause when docker-compose up fails
==COMMIT_MSG==

Include lastException as cause when docker-compose up fails

---

changelog/@unreleased/pr-741.v2.yml
docker-compose-rule-core/src/main/java/com/palantir/docker/compose/configuration/ProjectName.java
docker-compose-rule-core/src/test/java/com/palantir/docker/compose/configuration/ProjectNameShould.java

The project name validation no longer matches the Docker Compose behaivor.
https://github.com/docker/compose/pull/5788
Docker Compose will normalize project names if they do not conform to it's requirements.
This is better for consumers because it means they can use the same project names in tests and when running Docker Compose manually.

Remove project name validation
