palantir/docker-compose-rule

.gitignore, build.gradle, src/main/java/com/palantir/docker/compose/configuration/DockerComposeProjectName.java, src/main/java/com/palantir/docker/compose/execution/DockerCompose.java, src/main/java/com/palantir/docker/compose/execution/DockerComposeExecutable.java, src/test/java/com/palantir/docker/compose/logging/DockerCompositionLoggingIntegrationTest.java, src/test/java/com/palantir/docker/compose/matchers/IOMatchers.java
See #29.
Will stop concurrency problems occurring if running the same docker-compose.yml in a test in parallel.
=> Random project names

src/main/java/com/palantir/docker/compose/connection/ContainerNames.java, src/test/java/com/palantir/docker/compose/connection/ContainerNamesTest.java
=> Fix underscore bug in container names

README.md
Update so that examples in the README properly compile against the latest build of the library
=> Update code examples in README

circle.yml
Yeah, this sucks when it breaks the publish build :(
=> Run javadoc on PR builds

src/main/java/com/palantir/docker/compose/connection/waiting/Attempt.java, src/main/java/com/palantir/docker/compose/connection/waiting/SuccessOrFailure.java, src/test/java/com/palantir/docker/compose/connection/waiting/SuccessOrFailureShould.java
@CRogers can you merge this tomorrow if it looks good, would like to use it tomorrow.
=> Generate success or failure from lambda

gradle/idea.gradle
=> Remove custom Gradle IDEA JDK logic

README.md, src/main/java/com/palantir/docker/compose/execution/DefaultDockerCompose.java, src/test/java/com/palantir/docker/compose/execution/DockerComposeTest.java
=> Remove volumes as part of the rm command

src/main/java/com/palantir/docker/compose/execution/DefaultDockerCompose.java, src/test/java/com/palantir/docker/compose/execution/DockerComposeTest.java
=> Add volumes flag to down

src/main/java/com/palantir/docker/compose/connection/Container.java, src/main/java/com/palantir/docker/compose/connection/State.java, src/main/java/com/palantir/docker/compose/execution/DefaultDockerCompose.java, src/main/java/com/palantir/docker/compose/execution/DelegatingDockerCompose.java, src/main/java/com/palantir/docker/compose/execution/DockerCompose.java, src/test/java/com/palantir/docker/compose/DockerCompositionIntegrationTest.java, src/test/java/com/palantir/docker/compose/connection/StateShould.java, src/test/java/com/palantir/docker/compose/execution/DockerComposeShould.java
=> Implement start/stop/state for containers.

src/main/java/com/palantir/docker/compose/configuration/EnvironmentValidator.java, src/main/java/com/palantir/docker/compose/configuration/PackageVisible.java, src/main/java/com/palantir/docker/compose/configuration/ProjectName.java
This pull request fixes #96 the 'unknown enum constant' compile warning.
I also added some javadoc.
=> Fix unknown enum const

src/main/java/com/palantir/docker/compose/execution/Retryer.java, src/main/java/com/palantir/docker/compose/execution/RetryingDockerCompose.java, src/test/java/com/palantir/docker/compose/execution/RetryerShould.java
fixes https://github.com/palantir/docker-compose-rule/issues/90
=> Retryer waits 5 seconds before trying operation again

src/main/java/com/palantir/docker/compose/DockerComposeRule.java, src/main/java/com/palantir/docker/compose/DockerCompositionBuilder.java
=> Better builder class in DockerComposeRule

src/main/java/com/palantir/docker/compose/DockerComposeRule.java, src/main/java/com/palantir/docker/compose/configuration/ShutdownStrategy.java, src/main/java/com/palantir/docker/compose/execution/AggressiveShutdownStrategy.java, src/main/java/com/palantir/docker/compose/execution/GracefulShutdownStrategy.java, src/main/java/com/palantir/docker/compose/execution/SkipShutdownStrategy.java, src/test/java/com/palantir/docker/compose/DockerComposeRuleShould.java, src/test/java/com/palantir/docker/compose/DockerComposeRuleUpContainerIntegrationTest.java, src/test/resources/docker-compose.yaml
fixes #105
@jmcampanini cheeky CR?
=> add new AggressiveShutdownStrategy

build.gradle, circle.yml, src/main/java/com/palantir/docker/compose/DockerComposeRule.java, src/main/java/com/palantir/docker/compose/connection/waiting/ClusterWait.java, src/main/java/com/palantir/docker/compose/execution/AggressiveShutdownStrategy.java, src/main/java/com/palantir/docker/compose/execution/DefaultDockerCompose.java, src/main/java/com/palantir/docker/compose/execution/Retryer.java, src/main/java/com/palantir/docker/compose/execution/SkipShutdownStrategy.java, src/test/java/com/palantir/docker/compose/DockerComposeRuleShould.java, src/test/java/com/palantir/docker/compose/DockerComposeRuleUpContainerIntegrationTest.java, src/test/java/com/palantir/docker/compose/RemoveConflictingContainersIntegrationTest.java, src/test/java/com/palantir/docker/compose/execution/GracefulShutdownStrategyShould.java, src/test/java/com/palantir/docker/compose/execution/RetryerShould.java, src/test/resources/up-integration-test.yaml
Also includes a tiny bit of nicer logging.
Individual tests are faster now, and the overall build times are about 5m40.
=> Faster integration test

src/test/java/com/palantir/docker/compose/AggressiveShutdownWithNetworkCleanupStrategyIntegrationTest.java, src/test/java/com/palantir/docker/compose/AggressiveShutdownWithNetworkCleanupStrategyTest.java
=> Fix checkstyle issues

build.gradle
@j-baker this should fix #141 right?
=> Fix publishing variables

README.md
Our users are unlikely to want 'compile'
=> Recommend using testCompile in our docs

docker-compose-rule-core/src/main/java/com/palantir/docker/compose/configuration/ShutdownStrategy.java, docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/AggressiveShutdownStrategy.java, docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/AggressiveShutdownWithNetworkCleanupStrategy.java
Also JavaDoc the strategies. Part of #162
=> Deprecate Aggressive shutdown strategies

docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/Docker.java, docker-compose-rule-core/src/test/java/com/palantir/docker/compose/execution/DockerShould.java
This changes the regex for parsing the docker version to support the new YY.MM format (e.g. 17.03.0-ce). It also adds a non-static method in Docker for checking its version to allow for easier testing.
=> Add support for new YY.MM docker version format.

docker-compose-rule-core/src/main/java/com/palantir/docker/compose/connection/Container.java, docker-compose-rule-core/src/main/java/com/palantir/docker/compose/connection/DockerPort.java, docker-compose-rule-core/src/main/java/com/palantir/docker/compose/connection/waiting/Exceptions.java, docker-compose-rule-core/src/main/java/com/palantir/docker/compose/connection/waiting/SuccessOrFailure.java, docker-compose-rule-core/src/test/java/com/palantir/docker/compose/configuration/MockDockerEnvironment.java, docker-compose-rule-core/src/test/java/com/palantir/docker/compose/connection/waiting/ExceptionsShould.java
This way we print out what's actually going wrong with the connection rather than "it just didn't work"
=> Better error logging

docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/DefaultDockerCompose.java, docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/DelegatingDockerCompose.java, docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/DockerCompose.java
My project needs this to determine what needs building (and hence what gradle commands to run)
=> Add method to access docker-compose config

docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/DefaultDockerCompose.java, docker-compose-rule-core/src/main/java/com/palantir/docker/compose/logging/FileLogCollector.java, docker-compose-rule-core/src/test/java/com/palantir/docker/compose/execution/DockerComposeShould.java, gradle/wrapper/gradle-wrapper.properties
=> Wait for containers to be created before attaching to logs

.circleci/config.yml, .circleci/template.sh
add caching and correctly specify default branch
=> Re-render template

.baseline/checkstyle/checkstyle-suppressions.xml, .baseline/checkstyle/checkstyle.xml, build.gradle, docker-compose-rule-core/build.gradle, docker-compose-rule-core/src/main/java/com/palantir/docker/compose/configuration/AdditionalEnvironmentValidator.java, docker-compose-rule-core/src/main/java/com/palantir/docker/compose/connection/ContainerName.java, docker-compose-rule-core/src/main/java/com/palantir/docker/compose/connection/ContainerNames.java, docker-compose-rule-core/src/main/java/com/palantir/docker/compose/connection/DockerPort.java, docker-compose-rule-core/src/main/java/com/palantir/docker/compose/connection/Ports.java, docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/DockerCommandLocations.java, docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/DockerComposeExecutable.java, docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/DockerComposeVersion.java, docker-compose-rule-core/src/main/java/com/palantir/docker/compose/logging/DoNothingLogCollector.java, docker-compose-rule-core/src/test/java/com/palantir/docker/compose/configuration/ProjectNameShould.java, docker-compose-rule-core/src/test/java/com/palantir/docker/compose/matchers/IOMatchers.java, docker-compose-rule-junit4/build.gradle, docker-compose-rule-junit4/src/test/java/com/palantir/docker/compose/DockerComposeRuleShould.java, gradle.properties, versions.lock, versions.props
Update to latest baseline, use GCV
=> Update build system

docker-compose-rule-core/src/main/java/com/palantir/docker/compose/configuration/ShutdownStrategy.java, docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/CallbackThenDelegateShutdownStrategy.java, docker-compose-rule-core/src/test/java/com/palantir/docker/compose/execution/CallbackThenDelegateShutdownStrategyShould.java
this can be useful for gathering extra information from containers (copying files out, etc)
=> add shutdown strategy which calls a callback before shutting down

.github/PULL_REQUEST_TEMPLATE.md, build.gradle, docker-compose-rule-core/build.gradle, docker-compose-rule-junit4/build.gradle, gradle.properties, versions.lock, versions.props
Remove any lingering inline versions, remove all version properties and reduce boilerplate
=> Cleanup more of the build system
